# PyTorch Fundamentals 00

My latest work from Daniel Bourke's "Learn PyTorch for deep learning in a day. Literally." YouTube course. This work is relevant from minutes 0:00 to 2:48:56 YouTube time stamps (as of date 03/24/2023). The tutorial can be found here: https://www.youtube.com/watch?v=Z_ikDlimN6A 

Import modules:

In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Test module importations, versions, and implement a test-Tensor:

In [49]:
my_tensor = torch.Tensor([1,2,3,4,5])

print("PyTorch version: "+str(torch.__version__))
print("Pandas version: "+str(pd.__version__))
print("NumPy version: "+str(np.__version__))
print(my_tensor)

PyTorch version: 2.0.0+cpu
Pandas version: 1.5.3
NumPy version: 1.24.2
tensor([1., 2., 3., 4., 5.])


Check Nvidia SMI:

In [50]:
!nvidia-smi

Fri Mar 24 20:22:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.37       Driver Version: 527.37       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0    12W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors:

### Creating Tensors

In [51]:
# scalar

sclr = torch.tensor(7)
sclr

tensor(7)

PyTorch tensors created using 'torch.Tensor()'

In [52]:
# check number of dimensions sclr has

sclr.ndim

0

In [53]:
# get tensor as Python int type

sclr.item()

7

In [54]:
#Vector

vctr = torch.tensor([7,7])
vctr

tensor([7, 7])

In [55]:
#vector number of dimensions (has 1)

vctr.ndim

1

In [56]:
# Matrix

MTRX = torch.tensor([[7,8],
                     [9, 10]])
MTRX

tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
# Matrix number of dimensions (2)

MTRX.ndim

2

In [58]:
print(MTRX[0])

print(MTRX[1])

tensor([7, 8])
tensor([ 9, 10])


In [59]:
MTRX.shape

torch.Size([2, 2])

In [60]:
# TENSOR

TNSR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

TNSR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:
TNSR.ndim

3

In [62]:
TNSR.shape

torch.Size([1, 3, 3])

In [63]:
MY_TNSR = torch.tensor([[[1,3,5],
                         [2,4,6],
                         [3,7,11]]])

MY_TNSR

tensor([[[ 1,  3,  5],
         [ 2,  4,  6],
         [ 3,  7, 11]]])

#### Scalar:
- single number
- 0 dimensions
- lowercase nomenclature

#### Vector:
- number with *direction* but can have many other numbers
- 1 dimension
- lowercase nomenclature

#### Matrix:
- 2-d array of numbers
- 2 dimensions
- UPPERCASE nomenclature

#### Tensor:
- n-dimensional array of numbers
- any number of dimensions (Scalers, Vectors and Matrices are all Tensors too)
- UPPERCASE nomenclature

In [64]:
TNSR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random Tensors:

Why random tensors?

- The way many neural nets learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

torch.rand documentation - https://pytorch.org/docs/stable/generated/torch.rand.html 

Steps for random tensors:

1. Start with random numbers
2. Look at data
3. Update random numbers
4. Look at data
5. Update random numbers
6. ...

In [65]:
# Create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7120, 0.6682, 0.0685, 0.7282],
        [0.6490, 0.0695, 0.6289, 0.4256],
        [0.8075, 0.6633, 0.2401, 0.2020]])

In [66]:
random_tensor.ndim

2

In [67]:
# random tensor with similar shape to image tensor

random_image_tensor = torch.rand(size = (224, 224, 3))

random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [68]:
torch.rand(size=(3,3))

tensor([[0.9713, 0.0889, 0.2385],
        [0.9318, 0.4640, 0.1444],
        [0.7714, 0.5974, 0.8314]])

In [69]:
torch.rand(3,3)

tensor([[0.9787, 0.0359, 0.8524],
        [0.8750, 0.6360, 0.5584],
        [0.0664, 0.5962, 0.5193]])

In [70]:
# tensor of all zeros

zero_tensor = torch.zeros(size=(3,4))

zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
# Create tensor of all ones

ones_tensor = torch.ones(size=(3,4))

ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
# data type of ones_tensor

ones_tensor.dtype

torch.float32

#### Ranges of Tensors

(torch.range() will be depricated in further release, so use torch.arange() instead)

In [73]:
# use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [75]:
# creating tensors like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

One of the three big errors you'll run into with PyTorch and DL in general:

1. Tensors not of right datatype
2. Tensors not of right shape
3. Tensors not on right device

In [76]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_32_tensor.dtype

torch.float32

In [78]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [79]:
float_32_tensor.dtype

torch.float16

In [80]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)

''' 
dtype - what datatype is the tensor
device - what device is your tensor on (ex. "cpu", "cuda", None, etc)
requires_grad - whether or not to track gradients 
'''
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [82]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [83]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.int32)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9], dtype=torch.int32)
tensor([ 9., 36., 81.], dtype=torch.float16)


In [84]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.int64)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9])
tensor([ 9., 36., 81.], dtype=torch.float16)


In [85]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.long)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9])
tensor([ 9., 36., 81.], dtype=torch.float16)


#### Getting Information from Tensors

Tensors not of right data type:
- use "tensor.dtype"

Tensors not of right shape:
- use "tensor.shape"

Tensors not on the right device
- use "tensor.device"

In [86]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0274, 0.0740, 0.7445, 0.2521],
        [0.3474, 0.0764, 0.0268, 0.8640],
        [0.9816, 0.1748, 0.4916, 0.7969]])

In [87]:
# .size() and .shape produce same result

some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [88]:
# find out some details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0274, 0.0740, 0.7445, 0.2521],
        [0.3474, 0.0764, 0.0268, 0.8640],
        [0.9816, 0.1748, 0.4916, 0.7969]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Practice:

In [89]:
my_tensor = torch.rand(size=(10,5))

print(f"my_tensor:\t{my_tensor} +\n")

print(f"Type of my_tensor:\t{my_tensor.dtype}")
print(f"Shape of my_tensor:\t{my_tensor.shape}")
print(f"Device my_tensor is on:\t{my_tensor.device}")

my_tensor:	tensor([[0.9265, 0.8875, 0.6787, 0.6186, 0.4103],
        [0.5795, 0.7627, 0.8184, 0.0601, 0.8072],
        [0.9706, 0.5327, 0.5161, 0.4800, 0.4950],
        [0.6128, 0.7683, 0.2990, 0.3646, 0.5417],
        [0.0573, 0.2475, 0.8293, 0.8444, 0.5434],
        [0.0261, 0.5441, 0.2767, 0.7988, 0.1950],
        [0.4008, 0.9488, 0.7275, 0.5971, 0.1455],
        [0.6535, 0.7159, 0.3263, 0.2004, 0.0868],
        [0.3844, 0.1556, 0.8455, 0.8819, 0.2249],
        [0.9437, 0.6252, 0.5599, 0.2168, 0.7423]]) +

Type of my_tensor:	torch.float32
Shape of my_tensor:	torch.Size([10, 5])
Device my_tensor is on:	cpu


### Manipulating Tensors: Tensor Operations

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [90]:
my_tensor = torch.tensor([1,2,3])
my_tensor +10

tensor([11, 12, 13])

In [91]:
print(my_tensor * 10)
print(my_tensor+1)

tensor([10, 20, 30])
tensor([2, 3, 4])


In [92]:
my_tensor *=10
print(my_tensor)
print(my_tensor + 1)

tensor([10, 20, 30])
tensor([11, 21, 31])


In [93]:
print(my_tensor - 10)
print(my_tensor)
my_tensor -= 10
print(my_tensor)

tensor([ 0, 10, 20])
tensor([10, 20, 30])
tensor([ 0, 10, 20])


#### How to Multiply Matrices:

Two main ways of performing multiplcation on neural nets and DL:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules for performing matrix multiplication:

1. The *inner* dimensions must match:
- (3,2) @ (2,3) is good
- (3,2) @ (3,2) is not good.
2. The resulting matrix has the shape of the *outer* dimensions
- (3,2)@(2,3) produces tensor of shape 3x3

more information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html 

In [94]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3628, 0.2685, 0.3011],
        [0.8984, 0.6174, 0.7730],
        [0.5189, 0.3449, 0.4531]])

In [ ]:
# Element-wise multiplication

print(my_tensor,"*",my_tensor)
print(f"Equals: {my_tensor * my_tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals: tensor([  0, 100, 400])


In [ ]:
# Matrix multiplication

torch.matmul(my_tensor, my_tensor)

tensor(500)

In [ ]:
my_tensor

tensor([ 0, 10, 20])

In [ ]:
# Matrix multiplication by hand

0*0 + 10*10 + 20*20

500

In [ ]:
%%time
value = 0
for i in range(len(my_tensor)):
    value += my_tensor[i] * my_tensor[i]

value

CPU times: total: 0 ns
Wall time: 1 ms


tensor(500)

In [ ]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(500)

One of the most common errors in deep learning is *SHAPE* errors

In [ ]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

# torch.mm() == torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a *transpose*.

A *transpose* switches the axes *or* dimensions of a tensor.

In [ ]:
tensor_B.T, tensor_B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [ ]:
print(f"Tensor B shape:\t\t\t{tensor_B.shape}")
print(f"Tensor B shape transposed:\t{tensor_B.T.shape}")

Tensor B shape:			torch.Size([3, 2])
Tensor B shape transposed:	torch.Size([2, 3])


In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

#### Tensor Aggregation

Tensor Aggregation:
- Finding the ___ of the tensor:
    - mean
    - min
    - max
    - sum
    - etc

In [ ]:
# create tensor
# agg_tensor = aggregation tensor

agg_tensor = torch.arange(0,100,10)
agg_tensor, agg_tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(agg_tensor), agg_tensor.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(agg_tensor), agg_tensor.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(agg_tensor.type(torch.float32))

tensor(45.)

In [ ]:
agg_tensor.type(torch.float32).mean()

tensor(45.)

In [ ]:
agg_tensor.sum()

tensor(450)

In [ ]:
torch.sum(agg_tensor)

tensor(450)