# PyTorch Fundamentals 00

Import modules:

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Test module importations, versions, and implement a test-Tensor:

In [2]:
my_tensor = torch.Tensor([1,2,3,4,5])

print("PyTorch version: "+str(torch.__version__))
print("Pandas version: "+str(pd.__version__))
print("NumPy version: "+str(np.__version__))
print(my_tensor)

PyTorch version: 2.0.0+cpu
Pandas version: 1.5.3
NumPy version: 1.24.2
tensor([1., 2., 3., 4., 5.])


Check Nvidia SMI:

In [3]:
!nvidia-smi

Mon Mar 20 15:07:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.37       Driver Version: 527.37       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   59C    P0    13W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors:

### Creating Tensors

In [4]:
# scalar

sclr = torch.tensor(7)
sclr

tensor(7)

PyTorch tensors created using 'torch.Tensor()'

In [5]:
# check number of dimensions sclr has

sclr.ndim

0

In [6]:
# get tensor as Python int type

sclr.item()

7

In [7]:
#Vector

vctr = torch.tensor([7,7])
vctr

tensor([7, 7])

In [8]:
#vector number of dimensions (has 1)

vctr.ndim

1

In [9]:
# Matrix

MTRX = torch.tensor([[7,8],
                     [9, 10]])
MTRX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Matrix number of dimensions (2)

MTRX.ndim

2

In [11]:
print(MTRX[0])

print(MTRX[1])

tensor([7, 8])
tensor([ 9, 10])


In [12]:
MTRX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TNSR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

TNSR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TNSR.ndim

3

In [15]:
TNSR.shape

torch.Size([1, 3, 3])

In [16]:
MY_TNSR = torch.tensor([[[1,3,5],
                         [2,4,6],
                         [3,7,11]]])

MY_TNSR

tensor([[[ 1,  3,  5],
         [ 2,  4,  6],
         [ 3,  7, 11]]])

#### Scalar:
- single number
- 0 dimensions
- lowercase nomenclature

#### Vector:
- number with *direction* but can have many other numbers
- 1 dimension
- lowercase nomenclature

#### Matrix:
- 2-d array of numbers
- 2 dimensions
- UPPERCASE nomenclature

#### Tensor:
- n-dimensional array of numbers
- any number of dimensions (Scalers, Vectors and Matrices are all Tensors too)
- UPPERCASE nomenclature

In [17]:
TNSR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random Tensors:

Why random tensors?

- The way many neural nets learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

torch.rand documentation - https://pytorch.org/docs/stable/generated/torch.rand.html 

Steps for random tensors:

1. Start with random numbers
2. Look at data
3. Update random numbers
4. Look at data
5. Update random numbers
6. ...

In [18]:
# Create random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[9.4514e-01, 5.5895e-01, 2.7199e-01, 6.5379e-01],
        [3.5060e-01, 5.0676e-04, 8.9986e-01, 1.1852e-01],
        [4.1024e-01, 1.3281e-01, 6.6750e-01, 9.2143e-04]])

In [19]:
random_tensor.ndim

2

In [20]:
# random tensor with similar shape to image tensor

random_image_tensor = torch.rand(size = (224, 224, 3))

random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(size=(3,3))

tensor([[0.0126, 0.7159, 0.8029],
        [0.8500, 0.8327, 0.3385],
        [0.2312, 0.5855, 0.1818]])

In [22]:
torch.rand(3,3)

tensor([[0.7624, 0.1589, 0.0962],
        [0.1712, 0.2361, 0.1539],
        [0.2110, 0.3802, 0.0758]])

In [23]:
# tensor of all zeros

zero_tensor = torch.zeros(size=(3,4))

zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create tensor of all ones

ones_tensor = torch.ones(size=(3,4))

ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
# data type of ones_tensor

ones_tensor.dtype

torch.float32

#### Ranges of Tensors

(torch.range() will be depricated in further release, so use torch.arange() instead)

In [26]:
# use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
# creating tensors like

ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

One of the three big errors you'll run into with PyTorch and DL in general:

1. Tensors not of right datatype
2. Tensors not of right shape
3. Tensors not on right device

In [29]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_32_tensor.dtype

torch.float16

In [33]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)

''' 
dtype - what datatype is the tensor
device - what device is your tensor on (ex. "cpu", "cuda", None, etc)
requires_grad - whether or not to track gradients 
'''
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [36]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.int32)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9], dtype=torch.int32)
tensor([ 9., 36., 81.], dtype=torch.float16)


In [37]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.int64)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9])
tensor([ 9., 36., 81.], dtype=torch.float16)


In [38]:
int_32_tensor = torch.tensor([3,6,9],
                          dtype=torch.long)
print(int_32_tensor)
print(float_32_tensor * int_32_tensor)

tensor([3, 6, 9])
tensor([ 9., 36., 81.], dtype=torch.float16)


#### Getting Information from Tensors

Tensors not of right data type:
- use "tensor.dtype"

Tensors not of right shape:
- use "tensor.shape"

Tensors not on the right device
- use "tensor.device"

In [39]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7658, 0.9045, 0.9013, 0.5034],
        [0.4267, 0.2693, 0.7130, 0.1223],
        [0.6379, 0.9509, 0.9353, 0.9298]])

In [40]:
# .size() and .shape produce same result

some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [41]:
# find out some details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7658, 0.9045, 0.9013, 0.5034],
        [0.4267, 0.2693, 0.7130, 0.1223],
        [0.6379, 0.9509, 0.9353, 0.9298]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Practice:

In [42]:
my_tensor = torch.rand(size=(10,5))

print(f"my_tensor:\t{my_tensor} +\n")

print(f"Type of my_tensor:\t{my_tensor.dtype}")
print(f"Shape of my_tensor:\t{my_tensor.shape}")
print(f"Device my_tensor is on:\t{my_tensor.device}")

my_tensor:	tensor([[0.2465, 0.0957, 0.0412, 0.4898, 0.3207],
        [0.1078, 0.8008, 0.2336, 0.9957, 0.0463],
        [0.5304, 0.3339, 0.6076, 0.0173, 0.4998],
        [0.2209, 0.6818, 0.9808, 0.5997, 0.5334],
        [0.1056, 0.3184, 0.0930, 0.3153, 0.6060],
        [0.6740, 0.2480, 0.4384, 0.9053, 0.0181],
        [0.9224, 0.0542, 0.0312, 0.9773, 0.8398],
        [0.1153, 0.8096, 0.1957, 0.4198, 0.5149],
        [0.5217, 0.5222, 0.3955, 0.0572, 0.5413],
        [0.2684, 0.5417, 0.4154, 0.6438, 0.6638]]) +

Type of my_tensor:	torch.float32
Shape of my_tensor:	torch.Size([10, 5])
Device my_tensor is on:	cpu


### Manipulating Tensors: Tensor Operations

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [43]:
my_tensor = torch.tensor([1,2,3])
my_tensor +10

tensor([11, 12, 13])

In [44]:
print(my_tensor * 10)
print(my_tensor+1)

tensor([10, 20, 30])
tensor([2, 3, 4])


In [45]:
my_tensor *=10
print(my_tensor)
print(my_tensor + 1)

tensor([10, 20, 30])
tensor([11, 21, 31])


In [46]:
print(my_tensor - 10)
print(my_tensor)
my_tensor -= 10
print(my_tensor)

tensor([ 0, 10, 20])
tensor([10, 20, 30])
tensor([ 0, 10, 20])


#### How to Multiply Matrices:

Two main ways of performing multiplcation on neural nets and DL:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules for performing matrix multiplication:

1. The *inner* dimensions must match:
- (3,2) @ (2,3) is good
- (3,2) @ (3,2) is not good.
2. The resulting matrix has the shape of the *outer* dimensions
- (3,2)@(2,3) produces tensor of shape 3x3

more information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html 

In [53]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3628, 0.2685, 0.3011],
        [0.8984, 0.6174, 0.7730],
        [0.5189, 0.3449, 0.4531]])

In [47]:
# Element-wise multiplication

print(my_tensor,"*",my_tensor)
print(f"Equals: {my_tensor * my_tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals: tensor([  0, 100, 400])


In [48]:
# Matrix multiplication

torch.matmul(my_tensor, my_tensor)

tensor(500)

In [49]:
my_tensor

tensor([ 0, 10, 20])

In [50]:
# Matrix multiplication by hand

0*0 + 10*10 + 20*20

500

In [51]:
%%time
value = 0
for i in range(len(my_tensor)):
    value += my_tensor[i] * my_tensor[i]

value

CPU times: total: 0 ns
Wall time: 1 ms


tensor(500)

In [52]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(500)

One of the most common errors in deep learning is *SHAPE* errors

In [55]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.mm(tensor_A, tensor_B)

# torch.mm() == torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a *transpose*.

A *transpose* switches the axes *or* dimensions of a tensor.

In [57]:
tensor_B.T, tensor_B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [62]:
print(f"Tensor B shape:\t\t\t{tensor_B.shape}")
print(f"Tensor B shape transposed:\t{tensor_B.T.shape}")

Tensor B shape:			torch.Size([3, 2])
Tensor B shape transposed:	torch.Size([2, 3])


In [64]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [65]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])